### ISSUE TITLE
Module fails di:compile on Magento 2.2.0

### ISSUE THREAD

**Issue by magelife** [magefan/module-wysiwyg-advanced#1]
Blog module installs this as a dependency. On compile, error is thrown on ActiveEditor: 

  Class Magento\Ui\Block\Wysiwyg\ActiveEditor does not exist  

module-community is listed as a dependency for module-blog but not the wysiwyg. I'm stuck until I can get this to compile. 

composer forces installation of this dependency even on Magento 2.2.

**Comment by magefan** [comment]
@magelife , thank you for your report. Please try to use this fix
https://github.com/magefan/module-wysiwyg-advanced/commit/4a0a50aa97c25ab9477bde09755369419d04f519

Let us know if it works well for you.

**Comment by magefan** [comment]
@magelife , we have released a new version 2.0.4 with the fix

**Comment by dev1983** [comment]
which plugin it is 2.0.4 ? or how i have to install it and what location. I am not a developer but trying to setuo a store in magento.

**Comment by magefan** [comment]
@dev1983 , this plugin https://github.com/magefan/module-wysiwyg-advanced
https://github.com/magefan/module-wysiwyg-advanced/releases
