### ISSUE TITLE
Setup upgrade issue

### ISSUE THREAD

**Issue by djbolya** [magefan/module-wysiwyg-advanced#12]
Hi....You have a typo issue which throws error when you try to setup:upgrade magento.

> File: etc/module.xml

Line: 10

From:

`<module name="Magefan_WysiwygAdvanced" setup_version="2.0.8>`

To:

<`module name="Magefan_WysiwygAdvanced" setup_version="2.0.8">`

**Comment by niels-hubs** [comment]
@djbolya Duplicate, already reported at #9

**Comment by magefan** [comment]
Fixed in the latest version
