### ISSUE TITLE
wysiwyg-editor for transactional emails

### ISSUE THREAD

**Issue by gino2014** [magefan/module-wysiwyg-advanced#14]
First of all i would like to say thank you to the development team. As a suggestetion i would like to ask for an implemention for Magento transactional emails. Maybe it is possible or you could advice a workaround.

Kind regards
Gino

**Comment by ihorvansach** [comment]
@gino2014 ,  thank you for your feedback. Unfortunately, we do not plan to add such feature, as  transaction emails templates involves "loops", "if", etc. statements and this can bring the issues when using WYSIWYG editor.
