### ISSUE TITLE
Iterator.php line 63 error

### ISSUE THREAD

**Issue by EnigmaWebdesign** [magefan/module-wysiwyg-advanced#15]
Dear sir/madam,

I have installed the WYSIWYG editor in Magento 2.3.5p2 and now I get this error:

1 exception(s):
Exception #0 (Exception): Notice: Undefined index: id in /var/www/mag2riet.magetest.nl/public_html/vendor/magento/module-config/Model/Config/Structure/Element/Iterator.php on line 63

I only have installed this extension on a fresh Magento 2.3.5p2 installation.

Cheers,

Steve

**Comment by ihorvansach** [comment]
There recommended method to install the extension is via the composer

composer require magefan/module-wysiwyg-advanced
php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento setup:static-content:deploy -f

But you installed it Manually by uploading the archive to app/code folder and forgot to install dependencies. If you take a look into the file
app/code/Magefan/WysiwygAdvanced/composer.json
you will see that the extension also require megafan/module-community module to be installed. Please install the Magefan Community module (https://github.com/magefan/module-community ) to makes the WysiwygAdvanced works properly.
