### ISSUE TITLE
when ever it's di:compile it's generates error!

### ISSUE THREAD

**Issue by arun-magento** [magefan/module-wysiwyg-advanced#16]
C:\xampp\htdocs\my_project>php bin/magento setup:di:compile
Compilation was started.
%message% 0/7 [>---------------------------]   0% < 1 sec 60.0 MiB%message% 0/7
[>---------------------------]   0% < 1 sec 60.0 MiBProxies code generation... 0
/7 [>------------------------]   0% < 1 sec 60.0 MiB
Proxies code generation... 1/7 [===>---------------------]  14% 1 sec 64.0 MiB
Repositories code generation... 1/7 [===>------------------]  14% 1 sec 64.0 MiB
PHP Fatal error:  Class 'Magefan\Community\Block\Adminhtml\System\Config\Form\In
fo' not found in C:\xampp\htdocs\my_project\app\code\Magefan\WysiwygAdvance
d\Block\Adminhtml\System\Config\Form\Info.php on line 14
Fatal error: Class 'Magefan\Community\Block\Adminhtml\System\Config\Form\Info' n
ot found in C:\xampp\htdocs\my_project\app\code\Magefan\WysiwygAdvanced\Blo
ck\Adminhtml\System\Config\Form\Info.php on line 14

**Comment by magefan** [comment]
@arun-magento , please make sure that you have also installed https://github.com/magefan/module-community . This module is in the required list https://github.com/magefan/module-wysiwyg-advanced/blob/master/composer.json
