### ISSUE TITLE
What does the latest release do?

### ISSUE THREAD

**Issue by peterjaap** [magefan/module-wysiwyg-advanced#20]
In 2.0.11, the `Plugin/Magento/PageBuilder/Model/ConfigInterface.php` plugin was added.

See the compare between 2.0.10 and 2.0.11 here; https://github.com/magefan/module-wysiwyg-advanced/compare/2.0.10...2.0.11

I can't find any PR or an issue that relates to this. There's also no comment and no release name/changelog.

Could you explain why this change has been done?

**Comment by peterjaap** [comment]
@magefan ?

**Comment by magefan** [comment]
@peterjaap , it was added to be able to disable page builder for certain pages and use WYSIWYG editor instead. To disable page builder e.g. for the CMS page need to go to stores > configuration > magefan extensions > WYSIWYG Advanced  > set WYSIWYG Editor on CMS Page as "Enabled by Default"
