### ISSUE TITLE
Still relevant after Magento 2.4.4 release?

### ISSUE THREAD

**Issue by magentox** [magefan/module-wysiwyg-advanced#21]
Knowing Magento 2.4.4 (just released) uses TinyMCE 5 and this extension works only with TinyMCE 4, is this extension still relevant or do you intend to update it to make it work with Magento 2.4.4?

**Comment by peterjaap** [comment]
@magefan ?

**Comment by magefan** [comment]
@magentox , @peterjaap , yes it is.

Today we've added support of TinyMCE 5 https://github.com/magefan/module-wysiwyg-advanced/commit/942d5036ab4d5780f2eb02ac965595696c560a09

Also using it you can disable the page builder and replace it with WYSIWYG editor for some pages.

**Comment by magefan** [comment]
@magentox , @peterjaap , released a new version https://github.com/magefan/module-wysiwyg-advanced/releases/tag/2.0.12 with Magento 2.4.4 compatability.
