### ISSUE TITLE
Has been already defined in

### ISSUE THREAD

**Issue by Kiwifu** [magefan/module-wysiwyg-advanced#27]
Hi,

I am always facing issue when want to install different extensions of megafan.

Always getting the error : 

> Autoload error: Module 'Magefan_AdminUserGuide' from '/app/code/Magefan/AdminUserGuide' has been already defined in '/vendor/magefan/module-admin-user-guide.

Can you fix this issue without delete the files manually everytime?

**Comment by magefan** [comment]
@Kiwifu , it's a common Magento issue when installing the modules, please read this article

https://magefan.com/blog/magento2-module-has-been-already-defined-in-vendor

The best solution for you is to remove duplicated module from app/code folder

**Comment by Kiwifu** [comment]
@magefan thank you for the reply.

I will do that.
