### ISSUE TITLE
Fullpage Plugin

### ISSUE THREAD

**Issue by bernd-reindl** [magefan/module-wysiwyg-advanced#3]
Hello,

you add the plugin "fullpage" to $settings['plugins'].
This plugin adds body and head tags to the code.
Magento did not save this tags. But they are visible when disabling the editor.

![editor](https://user-images.githubusercontent.com/2369089/67082151-d4431580-f198-11e9-995a-21dc243fc5d7.jpg)

**Comment by magefan** [comment]
@bernd-reindl , thank you for your report. We were not able to reproduce this issue on our end but we have removed fullpage plugin. Looks like it has no sense there.

Let us know if it's all fine now on your side.
