### ISSUE TITLE
Is this Magento 2.3.2+ compatible?

### ISSUE THREAD

**Issue by LiamKarlMitchell** [magefan/module-wysiwyg-advanced#6]
Running into some issues with official implementation of TinyMCE 4...

https://github.com/magento/magento2/issues/4536
https://github.com/magento/magento2/issues/12165

Last time I used this was on a Magento 2.2.0 site if I recall.
They upgraded TinyMCE but it still has problems it seems.

**Comment by magefan** [comment]
Yes, this extension works on 2.3.2
