### ISSUE TITLE
Missing " in module.xml

### ISSUE THREAD

**Issue by parvesh-r** [magefan/module-wysiwyg-advanced#9]
module-wysiwyg-advanced/etc/module.xml
Closing " is missing for setup_version

**Comment by niels-hubs** [comment]
Hahhahaha, what a garbage. How can mistakes like this that are so easy to catch happen? Shame on you Magefan.

**Comment by grebbekevin** [comment]
Update right now please. This bug breaks the webshop. You guys should check your code before pushing a new version!

**Comment by JKetelaar** [comment]
Same issue here... Applied the pull request patch using:
```!json
    "extra": {
        "patches": {
            "magefan/module-wysiwyg-advanced": {
                "Fixes https://github.com/magefan/module-wysiwyg-advanced/issues/9": "https://patch-diff.githubusercontent.com/raw/magefan/module-wysiwyg-advanced/pull/10.patch"
            }
        }
    }
```

**Comment by magefan** [comment]
fixed in the latest version
